
const DATA = {
  members: [
    { id: 'M001', name: 'Sandra Kowalski', dob: '1972-03-15', memberId: 'HC-2024-001', plan: 'Medicare Advantage Gold', status: 'Active', phone: '(602) 555-0142', email: 'sandra.k@email.com', address: '4821 W. Camelback Rd, Phoenix AZ 85031', provider: 'Dr. Elena Reyes', group: 'AZ Educators Health', language: 'English', pcp: 'Dr. Elena Reyes', lastContact: '2025-04-10', openCases: 2, avatar: 'SK', color: '#0078d4' },
    { id: 'M002', name: 'James Thornton', dob: '1958-11-28', memberId: 'HC-2024-002', plan: 'Medicaid Plus', status: 'Active', phone: '(602) 555-0188', email: 'j.thornton@email.com', address: '330 N 52nd St, Phoenix AZ 85008', provider: 'Dr. Marcus Webb', group: 'Maricopa County', language: 'English', pcp: 'Dr. Marcus Webb', lastContact: '2025-04-15', openCases: 1, avatar: 'JT', color: '#107c10' },
    { id: 'M003', name: 'Maria Guadalupe Torres', dob: '1985-07-02', memberId: 'HC-2024-003', plan: 'Commercial HMO', status: 'Active', phone: '(602) 555-0231', email: 'mg.torres@email.com', address: '9200 E. McDowell Rd, Scottsdale AZ 85257', provider: 'Dr. Priya Nair', group: 'Scottsdale USD', language: 'Spanish', pcp: 'Dr. Priya Nair', lastContact: '2025-04-18', openCases: 0, avatar: 'MT', color: '#8764b8' },
    { id: 'M004', name: 'Robert Chen', dob: '1965-09-14', memberId: 'HC-2024-004', plan: 'Medicare Advantage Silver', status: 'Pending', phone: '(602) 555-0309', email: 'r.chen@email.com', address: '1204 S. Rural Rd, Tempe AZ 85281', provider: 'Dr. Elena Reyes', group: 'Tempe City Employees', language: 'English', pcp: 'Dr. Elena Reyes', lastContact: '2025-04-12', openCases: 3, avatar: 'RC', color: '#d83b01' },
    { id: 'M005', name: 'Aisha Okafor', dob: '1990-01-30', memberId: 'HC-2024-005', plan: 'Commercial PPO', status: 'Active', phone: '(602) 555-0417', email: 'a.okafor@email.com', address: '7601 E. Roosevelt St, Scottsdale AZ 85257', provider: 'Dr. Nathan Cruz', group: 'Banner Health Network', language: 'English', pcp: 'Dr. Nathan Cruz', lastContact: '2025-04-20', openCases: 0, avatar: 'AO', color: '#038387' },
    { id: 'M006', name: 'David Fitzgerald', dob: '1948-06-22', memberId: 'HC-2024-006', plan: 'Medicare Advantage Gold', status: 'Inactive', phone: '(602) 555-0522', email: 'd.fitzgerald@email.com', address: '2100 W. Indian School Rd, Phoenix AZ 85015', provider: 'Dr. Marcus Webb', group: 'AZ Retirees Plan', language: 'English', pcp: 'Dr. Marcus Webb', lastContact: '2025-03-28', openCases: 1, avatar: 'DF', color: '#ca5010' },
    { id: 'M007', name: 'Yuki Tanaka', dob: '1978-12-05', memberId: 'HC-2024-007', plan: 'Commercial HMO', status: 'Active', phone: '(602) 555-0645', email: 'y.tanaka@email.com', address: '5500 N. 7th Ave, Phoenix AZ 85013', provider: 'Dr. Priya Nair', group: 'Intel AZ', language: 'English', pcp: 'Dr. Priya Nair', lastContact: '2025-04-19', openCases: 0, avatar: 'YT', color: '#0078d4' },
  ],
  providers: [
    { id: 'P001', name: 'Dr. Elena Reyes', specialty: 'Internal Medicine', npi: '1234567890', phone: '(602) 555-1001', email: 'e.reyes@phoenixmedical.com', address: '2222 E. Highland Ave, Phoenix AZ 85016', group: 'Phoenix Medical Group', status: 'In Network', memberCount: 312, avatar: 'ER', color: '#0078d4' },
    { id: 'P002', name: 'Dr. Marcus Webb', specialty: 'Family Medicine', npi: '2345678901', phone: '(602) 555-1002', email: 'm.webb@sunhealth.com', address: '4411 N. Central Ave, Phoenix AZ 85012', group: 'Sun Health Partners', status: 'In Network', memberCount: 287, avatar: 'MW', color: '#107c10' },
    { id: 'P003', name: 'Dr. Priya Nair', specialty: 'Pediatrics', npi: '3456789012', phone: '(480) 555-1003', email: 'p.nair@scottsdalepeds.com', address: '8900 E. Pinnacle Peak Rd, Scottsdale AZ 85255', group: 'Scottsdale Peds', status: 'In Network', memberCount: 198, avatar: 'PN', color: '#8764b8' },
    { id: 'P004', name: 'Dr. Nathan Cruz', specialty: 'Cardiology', npi: '4567890123', phone: '(602) 555-1004', email: 'n.cruz@azheartcare.com', address: '500 W. Thomas Rd, Phoenix AZ 85013', group: 'AZ Heart Care', status: 'Out of Network', memberCount: 89, avatar: 'NC', color: '#038387' },
  ],
  groups: [
    { id: 'G001', name: 'AZ Educators Health', type: 'Employer', contact: 'Patricia Mills', phone: '(602) 555-2001', memberCount: 1240, status: 'Active', effectiveDate: '2024-01-01', plan: 'Commercial HMO/PPO' },
    { id: 'G002', name: 'Maricopa County', type: 'Government', contact: 'David Ruiz', phone: '(602) 555-2002', memberCount: 3872, status: 'Active', effectiveDate: '2023-07-01', plan: 'Medicaid Plus' },
    { id: 'G003', name: 'Scottsdale USD', type: 'Employer', contact: 'Linda Park', phone: '(480) 555-2003', memberCount: 890, status: 'Active', effectiveDate: '2024-01-01', plan: 'Commercial HMO' },
    { id: 'G004', name: 'AZ Retirees Plan', type: 'Retiree', contact: 'George Simmons', phone: '(602) 555-2004', memberCount: 654, status: 'Active', effectiveDate: '2022-01-01', plan: 'Medicare Advantage' },
    { id: 'G005', name: 'Banner Health Network', type: 'Healthcare', contact: 'Susan Lee', phone: '(602) 555-2005', memberCount: 512, status: 'Active', effectiveDate: '2024-06-01', plan: 'Commercial PPO' },
  ],
  cases: [
    { id: 'CS-2025-0041', memberId: 'M001', memberName: 'Sandra Kowalski - Test', type: 'Authorization', priority: 'High', status: 'Open', department: 'Utilization Management', createdDate: '2025-04-18', dueDate: '2025-04-25', assignedTo: 'Tom Bradley', description: 'Prior auth request for MRI lumbar spine — member reporting chronic back pain.', notes: [{ date: '2025-04-18', by: 'Tom Bradley', text: 'Case opened. Awaiting clinical documentation from Dr. Reyes.' }, { date: '2025-04-20', by: 'Sandra K. (Member)', text: 'Called in — asking for update on auth status.' }] },
    { id: 'CS-2025-0038', memberId: 'M001', memberName: 'Sandra Kowalski - Test', type: 'Grievance', priority: 'Medium', status: 'In Review', department: 'Member Services', createdDate: '2025-04-10', dueDate: '2025-04-24', assignedTo: 'Lisa Nguyen', description: 'Member filed grievance regarding denial of physical therapy sessions.', notes: [{ date: '2025-04-10', by: 'Lisa Nguyen', text: 'Grievance received. Reviewing policy coverage terms.' }] },
    { id: 'CS-2025-0035', memberId: 'M004', memberName: 'Robert Chen', type: 'Appeal', priority: 'High', status: 'Open', department: 'Appeals & Grievances', createdDate: '2025-04-08', dueDate: '2025-04-22', assignedTo: 'Kevin Morris', description: 'Member appealing denial of out-of-network specialist visit.', notes: [{ date: '2025-04-08', by: 'Kevin Morris', text: 'Appeal filed. Requesting supporting documentation.' }, { date: '2025-04-15', by: 'Kevin Morris', text: 'Documents received. Under clinical review.' }] },
    { id: 'CS-2025-0029', memberId: 'M002', memberName: 'James Thornton', type: 'Billing', priority: 'Low', status: 'Pending', department: 'Billing', createdDate: '2025-04-01', dueDate: '2025-04-28', assignedTo: 'Amy Walsh', description: 'Member received unexpected bill for covered preventive services.', notes: [{ date: '2025-04-01', by: 'Amy Walsh', text: 'Billing discrepancy identified. Coordinating with claims team.' }] },
    { id: 'CS-2025-0022', memberId: 'M006', memberName: 'David Fitzgerald', type: 'Care Management', priority: 'Medium', status: 'In Review', department: 'Care Management', createdDate: '2025-03-28', dueDate: '2025-04-21', assignedTo: 'Nurse Rivera', description: 'Post-discharge follow up for CHF hospitalization.', notes: [{ date: '2025-03-28', by: 'Nurse Rivera', text: 'Initial contact made. Care plan review scheduled.' }, { date: '2025-04-05', by: 'Nurse Rivera', text: 'Care plan updated. Member stable.' }] },
    { id: 'CS-2025-0019', memberId: 'M004', memberName: 'Robert Chen', type: 'Authorization', priority: 'High', status: 'Closed', department: 'Utilization Management', createdDate: '2025-03-20', dueDate: '2025-03-27', assignedTo: 'Tom Bradley', description: 'Auth for cardiac stress test approved.', notes: [{ date: '2025-03-20', by: 'Tom Bradley', text: 'Auth submitted.' }, { date: '2025-03-24', by: 'Tom Bradley', text: 'Approved. Auth #AZ-884421.' }] },
    { id: 'CS-2025-0014', memberId: 'M004', memberName: 'Robert Chen', type: 'Complaint', priority: 'Medium', status: 'Closed', department: 'Member Services', createdDate: '2025-03-10', dueDate: '2025-03-17', assignedTo: 'Lisa Nguyen', description: 'Member complained about long wait times at in-network clinic.', notes: [{ date: '2025-03-10', by: 'Lisa Nguyen', text: 'Complaint logged. Forwarded to Quality.' }, { date: '2025-03-16', by: 'Lisa Nguyen', text: 'Quality team followed up. Resolution letter sent.' }] },
  ],
  calls: [
    { id: 'CALL-001', memberId: 'M001', memberName: 'Sandra Kowalski', agentId: 'AGT-12', agentName: 'Carlos Mendez', startTime: '10:32 AM', duration: '8:24', reason: 'Authorization Status', status: 'Active', notes: '', caseCreated: 'CS-2025-0041' },
    { id: 'CALL-002', memberId: 'M004', memberName: 'Robert Chen', agentId: 'AGT-08', agentName: 'Sarah Kim', startTime: '10:15 AM', duration: '12:05', reason: 'Billing Inquiry', status: 'Active', notes: '', caseCreated: null },
    { id: 'CALL-003', memberId: 'M007', memberName: 'Yuki Tanaka', agentId: 'AGT-15', agentName: 'Dave Torres', startTime: '09:58 AM', duration: '5:40', reason: 'Benefits Question', status: 'Wrap-Up', notes: '', caseCreated: null },
  ],
  workflows: [
    { id: 'WF-001', name: 'New Member Onboarding', department: 'Member Services', status: 'In Progress', assignedTo: 'Onboarding Team', steps: ['ID Verification', 'Plan Enrollment', 'PCP Assignment', 'Welcome Kit Sent', 'Orientation Call'], currentStep: 2, dueDate: '2025-04-28', member: 'Maria Guadalupe Torres' },
    { id: 'WF-002', name: 'Prior Authorization Review', department: 'Utilization Management', status: 'Pending Approval', assignedTo: 'Tom Bradley', steps: ['Request Received', 'Clinical Review', 'Medical Director Approval', 'Decision Issued', 'Member Notified'], currentStep: 3, dueDate: '2025-04-25', member: 'Sandra Kowalski' },
    { id: 'WF-003', name: 'Grievance Resolution', department: 'Appeals & Grievances', status: 'In Progress', assignedTo: 'Kevin Morris', steps: ['Grievance Filed', 'Acknowledgment Sent', 'Investigation', 'Resolution Drafted', 'Closed'], currentStep: 2, dueDate: '2025-04-24', member: 'Sandra Kowalski' },
    { id: 'WF-004', name: 'Care Transition - Post Discharge', department: 'Care Management', status: 'Completed', assignedTo: 'Nurse Rivera', steps: ['Discharge Alert', 'Contact Member', 'Care Plan Review', 'PCP Follow-Up Scheduled', 'Closed'], currentStep: 4, dueDate: '2025-04-15', member: 'David Fitzgerald' },
    { id: 'WF-005', name: 'Provider Credentialing', department: 'Provider Relations', status: 'In Progress', assignedTo: 'Amanda Price', steps: ['Application Received', 'License Verification', 'Background Check', 'Committee Review', 'Credentialed'], currentStep: 1, dueDate: '2025-05-10', member: null, provider: 'Dr. Nathan Cruz' },
  ],
  agents: [
    { id: 'AGT-12', name: 'Carlos Mendez', status: 'On Call', queue: 1 },
    { id: 'AGT-08', name: 'Sarah Kim', status: 'On Call', queue: 1 },
    { id: 'AGT-15', name: 'Dave Torres', status: 'Wrap-Up', queue: 0 },
    { id: 'AGT-03', name: 'Lisa Chen', status: 'Available', queue: 0 },
    { id: 'AGT-19', name: 'Mike Patel', status: 'Break', queue: 0 },
  ]
};
